/** Main cities of Paraguay for marketplace location filters. */
export const PARAGUAY_CITIES: string[] = [
  "Asunción",
  "Ciudad del Este",
  "Encarnación",
  "San Lorenzo",
  "Luque",
  "Capiatá",
  "Lambaré",
  "Fernando de la Mora",
  "Limpio",
  "Ñemby",
  "Mariano Roque Alonso",
  "Itauguá",
  "Villa Elisa",
  "San Antonio",
  "Pedro Juan Caballero",
  "Coronel Oviedo",
  "Villarrica",
  "Concepción",
  "Caaguazú",
  "Caacupé",
  "Paraguarí",
  "Pilar",
  "Hernandarias",
  "Presidente Franco",
  "Minga Guazú",
  "Salto del Guairá",
  "San Juan Bautista",
  "San Pedro",
  "Filadelfia",
  "Loma Plata",
];